<?php
$title = 'Outbox';
$this->headTitle($title);
$loggedFlag = false;
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>

<br>
<div>
<a href="<?php echo $this->url('messages',array('action'=>'send'))?>">Send A Message</a> -
<a href="<?php echo $this->url('messages',array('action'=>'inbox'))?>">Inbox</a> -
</div>

<table class="table">
     <tr>
         <th>Recipient</th>
         <th>Subject</th>
         <th>Date</th>
         <th>&nbsp;</th>
     </tr>
     <?php foreach ($this->paginator as $message) : // <-- change here! ?>
         <tr>
             
             <td><?php 
             foreach ($message->getRecipient() as $recipient){
                echo $this->escapeHtml($recipient->getUsername()).'<br>';
             }
             ?></td>
             <td><?php echo $this->escapeHtml($message->getSubject());?></td>
             <td><?php echo $this->escapeHtml($message->getSent()->format('Y-m-d H:i:s'));?></td>
             
             <td><a href="<?php echo $this->url('messages',array('action'=>'view','id'=>$message->getId()));?>">Read</a>-
             <a href="<?php echo $this->url('messages',array('action'=>'delete','id'=>$message->getId()));?>">Delete</a></td>
         </tr>
     <?php endforeach; ?>
 </table>
    <?php ///* 
echo $this->paginationControl(
    $this->paginator, 'Sliding', 'pagination/sliding', array('route'=>'messages','action'=>'inbox')
);
      //*/
?>
</div>
