<?php 
echo $this->inlineScript()->prependFile($this->basePath('js/send.js'));

?>
<?php
$title = 'Send a message';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>
<?php
$form->prepare();
//$form->setAttribute('action', 'edit');
//$form->setAttribute('method', 'post');

 echo $this->form()->openTag($form);
 
 ?>
    <div class="row">
  <div id="fields" class="col-md-5">
 <?php foreach ($form as $element) : ?>

     <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?> ">
         <?php
        
             
            if ('submit' != $element->getAttribute('type')) {?>
                 
                 <label class="control-label"><?php echo $element->getLabel() ?></label>
                 <?php
                 $element//->setAttribute('class', 'form-control')
                         ->setAttribute('placeholder', $element->getLabel());
                 
             } else {
                 $element->setAttribute('class', 'btn btn-success');
             }
             if ($element instanceof Zend\Form\Element\Captcha) {
                 echo $this->formCaptcha($element);
             } else {
                 echo $this->formElement($element);
             }
             if ($this->formElementErrors($element)) : ?>
                 <?php
                 echo $this->formElementErrors()
                     ->setMessageOpenFormat('<p class="help-block">')
                     ->setMessageSeparatorString('</p><p class="help-block">')
                     ->setMessageCloseString('</p>')
                     ->render($element);
                 ?>
             <?php endif; ?>
     </div>
  
 <?php
endforeach;?>
    <?php 

echo $this->form()->closeTag() ?>
</div>