<?php
$title = 'Create Song STEP 3';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
 
$form->prepare();

 echo $this->form()->openTag($form);

 ?>
 <?php foreach ($form as $element) : ?>

     <div style="width: 330px;" class="form-group">

                
                <label  class="control-label"><?php echo $element->getLabel(); ?></label>   
       
                             
            
                 <?php
                 
                 $element->setAttribute('class', 'btn btn-success');
             
                 echo $this->formElement($element);
             
                 ?>
     </div>
  
 <?php
endforeach;
echo $this->form()->closeTag() ?>
