<?php
$title = 'Delete Song '.$this->song->getName();
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
 
$form->prepare();
//$form->setAttribute('action', $this->url('zfcuser', array('action' => 'addprofile')));
$form->setAttribute('method', 'post');

 echo $this->form()->openTag($form);

 ?>
 Are you sure? 
 <?php foreach ($form as $element) : ?>

     <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
         <?php
        
             
            if('file' == $element->getAttribute('type')){?>
                          <label class="control-label"><?php echo $element->getLabel() ?></label>
            <?php }else if('checkbox' == $element->getAttribute('type')){ ?>
                
                <label  class="control-label"><?php echo $element->getLabel(); ?></label>   
       
                             
            <?php } else if ('submit' != $element->getAttribute('type')) { ?>
                 <label class="control-label"><?php echo $element->getLabel() ?></label>
                 <?php
                 $element->setAttribute('class', 'form-control')
                         ->setAttribute('placeholder', $element->getLabel());
             } 
             else {
                 $element->setAttribute('class', 'btn btn-success');
             }
             
             if('checkbox' != $element->getAttribute('type') || 'radio' != $element->getAttribute('type'))
                echo $this->formElement($element);
             
             if ($this->formElementErrors($element)) : ?>
                 <?php
                 echo $this->formElementErrors()
                     ->setMessageOpenFormat('<p class="help-block">')
                     ->setMessageSeparatorString('</p><p class="help-block">')
                     ->setMessageCloseString('</p>')
                     ->render($element);
                 ?>
             <?php endif; ?>
     </div>
  
 <?php
endforeach;
echo $this->form()->closeTag() ?>
