<?php
$title = 'Songs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>
<?php 
echo '<h3>Samples</h3>';

foreach($this->samples as $song){
	echo '<a href="'.$this->url('song',array('action'=>'view','id'=>$song->getId())).'">'.$song->getName().
	'</a> - '.$song->getSampleType().' - '.$song->getVersions()->first()->getCreated()->format('Y-m-d').'<br>';
}
echo '<hr>';
echo '<h3>Projects in progress</h3>';
foreach($this->projects as $song){
    if(sizeof($song->getVersions())>0){
        echo '<a href="'.$this->url('song',array('action'=>'view','id'=>$song->getId())).'">'.$song->getName().
    	'</a> - '.$song->getVersions()->first()->getCreated()->format('Y-m-d').'<br>';
    }else{
        echo '<a href="'.$this->url('song',array('action'=>'view','id'=>$song->getId())).'">'.$song->getName().
        '</a> - '.' NO AUDIO FILE'//$song->getVersions()->first()->getCreated()->format('Y-m-d')
        .'<br>';
    }
}
echo '<hr>';
echo '<h3>Finished Projects</h3>';
foreach($this->finishedProjects as $song){
	echo '<a href="'.$this->url('song',array('action'=>'view','id'=>$song->getId())).'">'.$song->getName().
	'</a> - '.$song->getVersions()->first()->getCreated()->format('Y-m-d').'<br>';
}
?>

</div>