<?php
$title = 'Upload Song Cover';
$this->headTitle($title);
$user = $this->zfcUserIdentity()->getId();
?>
<div class="page-header">
    <h1><?php echo $this->translate($title); ?></h1>
</div>

<?php
//$form = $this->uploadForm;
$form->prepare();
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>

<div class="container">
<div class="row">
        <?php foreach ($form as $element) : ?>

     <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
         <?php
        
             if('file' == $element->getAttribute('type')){?>
                          <label class="control-label"><?php echo $element->getLabel() ?></label>
                      <?php 
            }else if ('submit' != $element->getAttribute('type')) { ?>
                 <label class="control-label"><?php echo $element->getLabel() ?></label>
                 <?php
                 $element->setAttribute('class', 'form-control')
                         ->setAttribute('placeholder', $element->getLabel());
             } else {
                 $element->setAttribute('class', 'btn btn-success');
             }
             if ($element instanceof Zend\Form\Element\Captcha) {
                 echo $this->formCaptcha($element);
             } else {
                 echo $this->formElement($element);
             }
             if ($this->formElementErrors($element)) : ?>
                 <?php
                 echo $this->formElementErrors()
                     ->setMessageOpenFormat('<p class="help-block">')
                     ->setMessageSeparatorString('</p><p class="help-block">')
                     ->setMessageCloseString('</p>')
                     ->render($element);
                 ?>
             <?php endif; ?>
     </div>
  
 <?php
endforeach; 
echo $this->form()->closeTag(); ?>
</div>
</div>
