<?php 
echo $this->inlineScript()->prependFile($this->basePath('js/bank.js'));

?>

<div class="page-header">
    <h1><?php echo $this->translate('Get Paid!'); ?></h1>
</div>

 <?php
 
$form->prepare();
 echo $this->form()->openTag($form);
 
 ?>

 <?php foreach ($form as $element) : ?>

     <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
         <?php
        
            if ('submit' != $element->getAttribute('type')) { ?>
                 <label class="control-label"><?php echo $element->getLabel() ?></label><br>
            <?php
                 $element->setAttribute('placeholder', $element->getLabel());
             } else {
                 $element->setAttribute('class', 'btn btn-success');
             }
             
             if ('radio' != $element->getAttribute('type'))
                 echo $this->formElement($element);
             else{
                $this->formRadio()->setSeparator('<br>');
             	echo $this->formRadio($element);
             }
             
             if ($this->formElementErrors($element)) : ?>
                 <?php
                 echo $this->formElementErrors()
                     ->setMessageOpenFormat('<p class="help-block">')
                     ->setMessageSeparatorString('</p><p class="help-block">')
                     ->setMessageCloseString('</p>')
                     ->render($element);
                 ?>
             <?php endif; ?>
     </div>
  
 <?php
endforeach;
echo $this->form()->closeTag() ?>
