<?php
$title = 'Store';
$this->headTitle($title);
$loggedFlag = false;
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>
<br>
<!-- Test if the User is connected -->
<?php if(!$this->zfcUserIdentity()): ?>
    <!-- display the login form -->
    <?php echo $this->zfcUserLoginWidget(array('redirect'=>'store/album')); ?>
<?php else: ?>
    <?php $loggedFlag = true; ?>
<?php endif?>
<br>
<table class="table">
     <tr>
         <th>&nbsp;</th>
         <th>Name</th>
         <th>Description</th>
         <th>Price</th>
         <th>&nbsp;</th>
     </tr>
     <?php foreach ($this->paginator as $album) : // <-- change here! ?>
         <tr>
             <td><img src="<?php echo $album->getCoverurl()?>" height="100px" width="100px"></img></td>
             <td><?php echo $this->escapeHtml($album->getName());?></td>
             <td><?php echo $this->escapeHtml($album->getDescription());?></td>
             <td><?php echo $this->escapeHtml('$'.$album->getLastPrice()->getAmount());?></td>
             <td>
                <?php if($loggedFlag):?>
                 <a href="<?php echo $this->url('store',
                     array('action' => 'buyAlbum', 'id' => $album->getId()));?>">Add To Download List</a> - 
                 <a href="<?php echo $this->url('album',
                     array('action' => 'view', 'id' => $album->getId()));?>">View</a>
                <?php else:?>
                    <a href="<?php echo $this->url('zfcuser',
                     array('action' => 'login'));?>">Login to buy!</a>
                <?php endif?>
             </td>
         </tr>
     <?php endforeach; ?>
 </table>
    <?php ///* 
echo $this->paginationControl(
    $this->paginator, 'Sliding', 'pagination/sliding', array('route'=>'store','action'=>'list')
);
      //*/
?>
</div>
