<?php 
echo $this->inlineScript()->prependFile($this->basePath('js/paypal.js'));
echo $this->inlineScript()->prependFile('https://www.paypalobjects.com/js/external/dg.js');
?>

<?php
$title = 'Store';
$this->headTitle($title);
//require_once 'paypalfunctions.php';
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>
<p>Total Items: <?php echo $this->total_items;?></p>

<p>Total Sum: $<?php echo $this->total_sum?></p>
<p>
    <?php //var_dump($this->cart);?>
    <?php if(sizeof($this->cart) > 0):?>
        <ul>
        <?php foreach ($this->cart as $item_key =>$item_value ){?>
            <li><?php echo $item_value->getProduct()?> <a href="<?php echo $this->url('store',
                     array('action' => 'remove','token'=>$item_key));?>">Remove</a></li>
        <?php }?>
        </ul>
    <?php else:?>   
    There are no items to download
    <?php endif;?>
</p>
<?php //var_dump($this->cart)?>

</div>

<div>
<?php
 
$form->prepare();
//$form->setAttribute('action', $this->url('zfcuser', array('action' => 'addprofile')));
$form->setAttribute('action', 'checkout');
$form->setAttribute('method', 'post');

 echo $this->form()->openTag($form);

 ?>
	<input type='image' name='paypal_submit' id='paypal_submit'  src='https://www.paypal.com/en_US/i/btn/btn_dg_pay_w_paypal.gif' border='0' align='top' alt='Pay with PayPal'/>
 <?php
echo $this->form()->closeTag() ?>
</div>



<!-- Add Digital goods in-context experience. Ensure that this script is added before the closing of html body tag -->



