<?php
$title = 'Donwload';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div>
<table class="table">
     <tr>
         <th>&nbsp;</th>
         <th>Date</th>
         <th>Amount</th>
         <th>Songs</th>
     </tr>
     <?php 
     $counter=1;
     foreach ($this->paginator as $purchase) : // <-- change here! ?>
         <tr>
             <td><?php echo $this->escapeHtml($counter);?></td>
             <td><?php echo $this->escapeHtml($purchase->getDate()->format('Y-m-d H:i:s'));?></td>
             <td><?php echo $this->escapeHtml($purchase->getAmount());?></td>
             <td>
                 <p><?php foreach ($purchase->getSongs() as $song){
                 	  echo $this->escapeHtml($song->getName()).' <a href="'. $this->url('download',
                     array('action' => 'download', 'id' => $song->getId())).'">Download</a><br>';
                 }?>
                 </p>
             </td>
         </tr>
     <?php 
        $counter++;
     endforeach; ?>
 </table>
    <?php ///* 
echo $this->paginationControl(
    $this->paginator, 'Sliding', 'pagination/sliding', array('route'=>'store','action'=>'history')
);
      //*/
?>
</div>