<?php //echo $this->doctype(); ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Music Lackey'))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->prependStylesheet($this->basePath() . '/css/chosen/chosen.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
            ->prependStylesheet($this->basePath() . '/css/jquery-ui.min.css')?>

        <!-- Scripts -->
        <?php
        
        echo $this->headScript()
            //->prependFile($this->basePath() . '/js/select.js')
            ->prependFile($this->basePath() . '/js/chosen/chosen.jquery.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ));
        ?>

    </head>
<body>
    <div id="wrapper">
        <div id="header">
            <?php echo $this->menu()->setPartial(array('partial/example.phtml','Application'));?>
        </div>
        <div id="page">
            <div class="container">
                <?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)
                    ->setPartial(array('partial/breadcrumb.phtml','Application'));?>
                <?php echo $this->content; ?>
            </div><!-- /container -->
    	</div>
    	<div id="footer">
    		<hr>
    	</div>
    </div>
</body>
</html>
<?php echo $this->inlineScript();?>