<?php echo $this->inlineScript()->prependFile($this->basePath('js/search.js'));?>

<div class="page-header">
    <h1><?php echo $this->translate('Search'); ?></h1>
</div>
<div>
    <p></p>
</div>
<div class="row">
    <?php $form->prepare();
    $form->setAttribute('method', 'get');
    echo $this->form()->openTag($form); ?>
    <div id="fields" class="col-md-5">
    <?php foreach ($form as $element) : ?>
        <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?> ">
            <?php 
            if ('submit' != $element->getAttribute('type')) {?>
                 
                 <label class="control-label"><?php echo $element->getLabel() ?></label>
                 <?php
                 $element//->setAttribute('class', 'form-control')
                         ->setAttribute('placeholder', $element->getLabel());
                 
             } else {
                 $element->setAttribute('class', 'btn btn-success');
             }
             if ($element instanceof Zend\Form\Element\Captcha) {
                 echo $this->formCaptcha($element);
             } else {
                 echo $this->formElement($element);
             }
             if ($this->formElementErrors($element)) : ?>
                 <?php
                 echo $this->formElementErrors()
                     ->setMessageOpenFormat('<p class="help-block">')
                     ->setMessageSeparatorString('</p><p class="help-block">')
                     ->setMessageCloseString('</p>')
                     ->render($element);
                 ?>
             <?php endif; ?>
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>     
<div class="row">
<?php 
/*foreach($this->results as $result){
	echo $result->getUsername().' - '.$result->getDisplayname().'<br>';
}*/
?>
</div>
<div class="row">
<?php if(isset($this->paginator)){?>
<table class="table">
     <tr>
         <th>&nbsp;</th>
         <th>Name</th>
         <th>Authors</th>
         <th>Created</th>
         <th># songs</th>
         <th>&nbsp;</th>
     </tr>
     <?php foreach ($this->paginator as $album) : // <-- change here! ?>
         <tr>
             <td>
                <img src="<?php echo $album->getCoverurl()?>" height="100px" width="100px"></img>
             </td>
             
             <td>
                <a href="<?php echo $this->url('album',array('action'=>'view','id'=>$album->getId()));?>">
                    <?php echo $this->escapeHtml($album->getName());?>
                </a>
             </td>
             <td>
                <?php foreach($album->getUsers() as $user){
                	?>
                	<a href="<?php echo $this->url('profile',array('action'=>'index','id'=>$user->getId()));?>">
                        <?php echo $this->escapeHtml($user->getUsername());?>
                    </a>
                    <br>
                <?php }?>
             </td>
             <td><?php echo $this->escapeHtml($album->getCreated()->format('Y-m-d'));?></td>
             <td><?php echo $this->escapeHtml($album->getSongs()->count());?></td>
             <td>&nbsp;</td>
         </tr>
     <?php endforeach; ?>
 </table>
<?php ///* 
echo $this->paginationControl(
    $this->paginator, 'Sliding', 'pagination/get', array('route'=>'search','action'=>'albums','keyword'=>$this->keyword)
);
?>
<?php }?>
</div>

