<?php
$title = 'Most Popular!';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div style="height:20px"></div>
<div class="row">
    <div class="col-md-4" style="height: 700px">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Top Downloaded') ?></h3>
            </div>
            <div class="panel-body">
                <ul>
                <?php foreach ($this->topDownloaded as $result){
                    //var_dump($result->getName());
                	echo '<li><a href="'.$this->url('song',array('action'=>'view','id'=>$result->getId()))
                	.'">'.$result->getName().'</a></li>';
                }?>
                </ul>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Top Liked') ?></h3>
            </div>
            <div class="panel-body">
                <?php foreach ($this->topLiked as $result){
                	echo '<li><a href="'.$this->url('song',array('action'=>'view','id'=>$result->getId()))
                	.'">'.$result->getName().'</a></li>';
                }?>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Most popular unfinished projects!') ?></h3>
            </div>
            <div class="panel-body">
                <?php foreach ($this->topUnfinished as $result){
                	echo '<li><a href="'.$this->url('song',array('action'=>'view','id'=>$result->getId()))
                	.'">'.$result->getName().'</a></li>';
                }?>
            </div>
        </div>
    </div>
</div>

