<?php echo $this->inlineScript()->prependFile($this->basePath('js/search.js'));?>

<div class="page-header">
    <h1><?php echo $this->translate('Search'); ?></h1>
</div>
<div>
    <p>This search feature looks for users that has part of a keyword in their usernames, display names, given names and emails. Also if a genre is chosen.
    it will display users that have that particular genre in their favorite lists. <br>
    however this do NOT mean that the user has made or participated in a project of that genre.</p>
</div>
<div class="row">
    <?php $form->prepare();
    $form->setAttribute('method', 'get');
    echo $this->form()->openTag($form); ?>
    <div id="fields" class="col-md-5">
    <?php foreach ($form as $element) : ?>
        <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?> ">
            <?php 
            if ('submit' != $element->getAttribute('type')) {?>
                 
                 <label class="control-label"><?php echo $element->getLabel() ?></label>
                 <?php
                 $element//->setAttribute('class', 'form-control')
                         ->setAttribute('placeholder', $element->getLabel());
                 
             } else {
                 $element->setAttribute('class', 'btn btn-success');
             }
             if ($element instanceof Zend\Form\Element\Captcha) {
                 echo $this->formCaptcha($element);
             } else {
                 echo $this->formElement($element);
             }
             if ($this->formElementErrors($element)) : ?>
                 <?php
                 echo $this->formElementErrors()
                     ->setMessageOpenFormat('<p class="help-block">')
                     ->setMessageSeparatorString('</p><p class="help-block">')
                     ->setMessageCloseString('</p>')
                     ->render($element);
                 ?>
             <?php endif; ?>
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>     
<div class="row">
<?php 
/*foreach($this->results as $result){
	echo $result->getUsername().' - '.$result->getDisplayname().'<br>';
}*/
?>
</div>
<div class="row">
<?php if(isset($this->paginator)){?>
<table class="table">
     <tr>
         <th>Username</th>
         <th>Display Name</th>
         <th>Member since</th>
         <th># finished projects</th>
         <th># finished albums</th>
         <th>&nbsp;</th>
     </tr>
     <?php foreach ($this->paginator as $user) : // <-- change here! ?>
         <tr>
             <td>
                <a href="<?php echo $this->url('profile',array('action'=>'index','id'=>$user->getId()));?>">
                    <?php echo $this->escapeHtml($user->getUsername());?>
                </a>
             </td>
             <td><?php echo $this->escapeHtml($user->getDisplayName());?></td>
             <td><?php echo $this->escapeHtml($user->getCreated()->format('Y-m-d'));?></td>
             <td><?php echo $this->escapeHtml($user->countSongs());?></td>
             <td><?php echo $this->escapeHtml($user->getAlbums()->count());?></td>
         </tr>
     <?php endforeach; ?>
 </table>
<?php ///* 
echo $this->paginationControl(
    $this->paginator, 'Sliding', 'pagination/get', array('route'=>'search','action'=>'users','keyword'=>$this->keyword,'genre'=>$this->genre)
);
?>
<?php }?>
</div>

