

<?php
$title = $this->song->getName();
$this->headTitle($title. ' STEP 2');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<?php 
if($this->tempFile != null)
    var_dump($this->tempFile);
if($this->errors!= null)
    var_dump($this->errors);
?>



<?php
 
$form->prepare();
//$form->setAttribute('action', 'upload');
//$form->setAttribute('method', 'post');

 //echo 'Last version number used: '.$this->song->getVersions()->first()->getVersion();

 echo $this->form()->openTag($form);
 ?>

 <?php foreach ($form as $element) : ?>

     <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
         
         
         
         <?php
        
             
            if('file' == $element->getAttribute('type')){?>
                          <label class="control-label"><?php echo $element->getLabel() ?></label>
                      <?php 
            }else if ('submit' != $element->getAttribute('type') ) { 
                 if ('radio' != $element->getAttribute('type') ){?>
                     <label class="control-label"><?php echo $element->getLabel() ?></label>
                     <?php
                     $element->setAttribute('class', 'form-control')
                             ->setAttribute('placeholder', $element->getLabel());
                 }
             } 
             else {
                 $element->setAttribute('class', 'btn btn-success');
             }
             if ($element instanceof Zend\Form\Element\Radio) {
                 //echo $this->formRadio($element);
                 echo $this->ztbFormElement($element);
             } else {
                 echo $this->formElement($element);
             }
             if ($this->formElementErrors($element)) : ?>
                 <?php
                 echo $this->formElementErrors()
                     ->setMessageOpenFormat('<p class="help-block">')
                     ->setMessageSeparatorString('</p><p class="help-block">')
                     ->setMessageCloseString('</p>')
                     ->render($element);
                 ?>
             <?php endif; ?>
     </div>
  
 <?php
endforeach;
echo $this->form()->closeTag();
echo $this->errors; ?>


