<h1>Admin</h1>
<p><?php echo '<a href="'.$this->url('zfcadmin/users').'">Users</a><br>';?>
            <?php echo '<a href="'.$this->url('zfcadmin/songs').'">Songs</a><br>';?>
            <?php echo '<a href="'.$this->url('zfcadmin/newrole').'">Create New Roles</a>';?></p>
<p>This is the Admin interface. Create a view script which resolves to <code>zfc-admin/admin/index</code> to override this text. Create a view script for <code>layout/admin</code> to override this surrounding layout.</p>