<?php 
echo $this->inlineScript()->prependFile($this->basePath('js/profile.js'));

?>

<div class="page-header">
    <h1><?php echo $this->translate('User Profile'); ?></h1>
</div>

 <?php
 
$form->prepare();
$form->setAttribute('action', 'editprofile');
$form->setAttribute('method', 'post');

 echo $this->form()->openTag($form);
 
 ?>
    <div class="row">
  <div id="fields" class="col-md-5">
 <?php foreach ($form as $element) : ?>

     <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?> ">
         <?php
        
             
            if ('submit' != $element->getAttribute('type')) {?>
                 
                 <label class="control-label"><?php echo $element->getLabel() ?></label>
                 <?php
                 $element->setAttribute('class', 'form-control')
                         ->setAttribute('placeholder', $element->getLabel());
                 
             } else {
                 $element->setAttribute('class', 'btn btn-success');
             }
             if ($element instanceof Zend\Form\Element\Captcha) {
                 echo $this->formCaptcha($element);
             } else {
                 echo $this->formElement($element);
             }
             if ($this->formElementErrors($element)) : ?>
                 <?php
                 echo $this->formElementErrors()
                     ->setMessageOpenFormat('<p class="help-block">')
                     ->setMessageSeparatorString('</p><p class="help-block">')
                     ->setMessageCloseString('</p>')
                     ->render($element);
                 ?>
             <?php endif; ?>
     </div>
  
 <?php
endforeach;?>
    </div>
<div style="width: 330px; height: 500px;" class="col-md-5">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Upload your Avatar!') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you are not using Gravatar please upload your own avatar and leave gravatar email field blank')) ?></p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('avatar',array('action'=>'upload'))?>"><?php echo $this->translate('Upload') ?> &raquo;</a></p>
            </div>
        </div>

     </div>
     
</div>

<?php 
echo $this->form()->closeTag() ?>