<?php
$title = 'Users homepage';
$this->headTitle($title);
$user = $this->zfcUserIdentity()->getId();
?>


<div class="page-header">
    <h1><?php echo $this->translate('User details'); ?></h1>
</div>
<div class="container">
<div class="row">
<div style="float:left; padding-right:16px;">
<?php 
if(isset($this->dataGravatar['useGravatar']))
    echo '<img src="'.$this->dataGravatar['imgURL'].'" height="100px" width="100px"></img>';
else
    echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>

</div>
<h3><?php echo $this->translate('Hello'); ?>, <?php 
if($this->zfcUserDisplayName()!='')
echo $this->zfcUserDisplayName();
else
    $this->zfcUserUsername();

?>!</h3>
<p>
	Add <a href="<?php echo $this->url('zfcuser/addprofile') ?>"><?php echo $this->translate('Profile') ?></a>
	Edit <a href="<?php echo $this->url('zfcuser/editprofile');?>">Profile</a><br>
     <a href="<?php echo $this->url('zfcuser/changepassword')?>"><?php echo $this->translate('Change Password'); ?></a><br>
     <a href="<?php echo $this->url('zfcuser/changeemail')?>"><?php echo $this->translate('Change Email'); ?></a>

 
</p>
<a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
</div>
</div>

