<?php
$title = 'Users homepage';
$this->headTitle($title);
$user = $this->zfcUserIdentity()->getId();
?>


<div class="page-header">
    <h1><?php echo $this->translate('User details'); ?></h1>
</div>
<div class="container">
<div class="row">
<div style="float:left; padding-right:16px;">
<?php 
if(isset($this->dataGravatar['useGravatar']))

    echo '<a href="'.$this->url('avatar',array('action'=>'upload')).'"><img src="'
		.$this->dataGravatar['imgURL'].'" height="100px" width="100px"></img></a>';
else
    echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>

</div>
<h3><?php echo $this->translate('Hello'); ?>, <?php 
if($this->zfcUserDisplayName()!='')
echo $this->zfcUserDisplayName();
else
    $this->zfcUserUsername();

?>!</h3>
<p>
	<!--<a href="<?php //echo $this->url('zfcuser/add') ?>"><?php //echo $this->translate('Add Profile') ?></a>
    <a href="<?php //echo $this->url('zfcuser/edit');?>">Edit Profile</a><br>-->
    <a href="<?php echo $this->url('profile',array('action'=>'add')); ?>"><?php echo $this->translate('Add Profile'); ?></a><br>
    <a href="<?php echo $this->url('profile',array('action'=>'edit'));?>">Edit Profile</a><br>
    <a href="<?php echo $this->url('profile',array('action'=>'index'));?>">Public Profile</a><br>
    <a href="<?php echo $this->url('profile',array('action'=>'index'));?>">Payment Information</a><br>
    <a href="<?php echo $this->url('zfcuser/changepassword')?>"><?php echo $this->translate('Change Password'); ?></a><br>
    <a href="<?php echo $this->url('zfcuser/changeemail')?>"><?php echo $this->translate('Change Email'); ?></a>

 
</p>
<a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
</div>
</div>

